NLB release to open source from release-1.19 / oci-ccm 0.13.0
l-technicore/oci-cloud-controller-manager pull request #1
Opened 2022-04-25 08:36 UTC by l-technicore

Release to Open Source from internal release-1.19 branch. Includes NLB feature and some other minor fixes and updates.

2022-04-26 05:39 UTC, mrunalpagnis requested changes
also, remove the changes made in .github folder

2022-04-26 05:39 UTC, mrunalpagnis commented on go.mod
> +	github.com/oracle/oci-go-sdk/v50 v50.1.0
keep only 1 version of oci-go-sdk

2022-04-26 05:39 UTC, mrunalpagnis commented on hack/test.sh
> +GO111MODULE=off HTTP_PROXY=http://www-proxy-hqdc.us.oracle.com/ go test -coverprofile=coverage.out -v -installsuffix "static" ${TARGETS}
remove proxy variable

2022-04-26 05:39 UTC, mrunalpagnis commented on pkg/cloudprovider/providers/oci/load_balancer_test.go
> +	"github.com/oracle/oci-cloud-controller-manager/pkg/oci/client"
oraganize imports

2022-04-26 05:39 UTC, mrunalpagnis commented on test/e2e/framework/seclist_util.go
> +	core "github.com/oracle/oci-go-sdk/v49/core"
can be 50 itself

2022-04-27 09:20 UTC, l-technicore commented on go.mod
> +	github.com/oracle/oci-go-sdk/v50 v50.1.0
Some old dependencies were remaining in test files, resolved now.

2022-04-27 09:21 UTC, l-technicore commented on pkg/cloudprovider/providers/oci/load_balancer_test.go
> +	"github.com/oracle/oci-cloud-controller-manager/pkg/oci/client"
Done

2022-04-27 09:22 UTC, l-technicore commented on test/e2e/framework/seclist_util.go
> +	core "github.com/oracle/oci-go-sdk/v49/core"
Resolved

2022-06-27 08:55 UTC, closed without merging